spin:
  thrust:
    description: 'Thrust value for idle spin on ground. Should be much less than 9.81*mass'
    type: float
    default: 2.0
    min: 0.0

model:
  vehicle_mass:
    description: 'Mass of the UAV'
    type: float
    default: 1.0
    min: 0.0

takeoff:
  altitude:
    description: 'Altitude to takeoff to'
    type: float
    default: 10.0
    min: 0.0
