spin:
  thrust:
    description: 'Thrust value for idle spin on ground. Should be much less than 9.81*mass'
    type: float
    default: 2.0
    min: 0.0

waypoint_tracker:
  velocity_gain:
    description: 'Gain to keep velocity high between waypoints.'
    type: float
    default: 0.5
    min: 0.0