limits:
  thrust:
    description: "Maximum thrust of the UAV"
    type: float
    default: 200.0
    min: 0.0

  ground_velocity:
    description: "Maximum ground velocity of the UAV"
    type: float
    default: 15.0
    min: 0.0

  vertical_velocity:
    description: "Maximum vertical velocity of the UAV"
    type: float
    default: 10.0
    min: 0.0

  global_velocity:
    description: "Maximum global velocity of the UAV"
    type: float
    default: 20.0
    min: 0.0

  ground_acceleration:
    description: "Maximum ground acceleration of the UAV"
    type: float
    default: 5.0
    min: 0.0

  vertical_acceleration:
    description: "Maximum vertical acceleration of the UAV"
    type: float
    default: 5.0
    min: 0.0

  global_acceleration:
    description: "Maximum global acceleration of the UAV"
    type: float
    default: 5.0
    min: 0.0

  angular_velocity_x:
    description: "Maximum angular velocity around the x-axis of the UAV"
    type: float
    default: 1.0
    min: 0.0

  angular_velocity_y:
    description: "Maximum angular velocity around the y-axis of the UAV"
    type: float
    default: 1.0
    min: 0.0

  angular_velocity_z:
    description: "Maximum angular velocity around the z-axis of the UAV"
    type: float
    default: 1.0
    min: 0.0

  angular_acceleration_z:
    description: "Maximum angular acceleration around the z-axis of the UAV"
    type: float
    default: 10.0
    min: 0.0

  min_z_acceleration:
    description: "Minimum z acceleration of the UAV"
    type: float
    default: -5.0
    max: -1.0

  max_angle:
    description: "Maximum angle of the UAV from vertical in degrees"
    type: float
    default: 120.0
    min: 0.0
    max: 180.0
