model:
  vehicle_mass:
    description: 'Mass of the UAV'
    type: float
    default: 1.0
    min: 0.0

  thrust_constant_coefficient:
    description: 'Thrust constant coefficient for thrust scaling'
    type: float
    default: 0.0

  thrust_linear_coefficient:
    description: 'Thrust linear coefficient for thrust scaling'
    type: float
    default: 0.0

  thrust_quadratic_coefficient:
    description: 'Thrust quadratic coefficient for thrust scaling'
    type: float
    default: 120.0
    min: 0.0