px4:
  thrust_constant_coefficient:
    description: 'Thrust constant coefficient'
    type: float
    default: 0.0

  thrust_linear_coefficient:
    description: 'Thrust linear coefficient'
    type: float
    default: 0.0

  thrust_quadratic_coefficient:
    description: 'Thrust quadratic coefficient'
    type: float
    default: 120.0
    min: 0.0