se3:
  position_gains:
    description: "Position gains for the SE3 controller"
    type: float
    default: [9.0, 9.0, 20.0]
    min: 0.0

  velocity_gains:
    description: "Velocity gains for the SE3 controller"
    type: float
    default: [6.0, 6.0, 9.0]
    min: 0.0

  min_z_acceleration:
    description: "Minimum z acceleration of the UAV"
    type: float
    default: -5.0
    max: -1.0

  max_angle:
    description: "Maximum angle of the UAV from vertical in degrees"
    type: float
    default: 40.0
    min: 0.0
    max: 180.0