se3:
  position_gains:
    description: "Position gains for the SE3 controller"
    type: float
    default: [4.0, 4.0, 4.0]
    min: 0.0

  velocity_gains:
    description: "Velocity gains for the SE3 controller"
    type: float
    default: [2.0, 2.0, 2.0]
    min: 0.0

#TODO(robotsix): Switch this to limits.yaml and include in the NLMPC
  min_z_acceleration:
    description: "Minimum z acceleration of the UAV"
    type: float
    default: -5.0
    max: -1.0
