pd:
  position_gains:
    description: "Position gains for the SE3 controller"
    type: float
    default: [4.0, 4.0, 4.0]
    min: 0.0

  velocity_gains:
    description: "Velocity gains for the SE3 controller"
    type: float
    default: [2.0, 2.0, 2.0]
    min: 0.0
